@startuml
'https://plantuml.com/class-diagram

class Ui {
-Divider: String
+printDivider(): void
+getUserInput(): void
+printWelcomeMessage(): void
+printExitMessage(): void
+printHelpPage(): void
+printAddSuccess(): void
+printListSuccess(): void
+printRemoveSuccess(): void
+printFilterFail(): void
+printInvalidCommand(): void
+printSaveFail(): void
+printTestModeStart(): void
+printTestModeEnd(): void
+printFileWriteError(): void
+printInvalidNote(): void
+printTopoSortSuccess(): void
}

FileManager --> "1  " Ui
FileManager *- "*" SingleFile
SingleFile --> "1 " Ui

Command --> Ui

AddCommand ..|> Command
ExitCommand ..|> Command
FilterCommand ..|> Command
HelpCommand ..|> Command
ListCommand ..|> Command
RemoveCommand ..|> Command
TestModeCommand ..|> Command
ExitTestModeCommand ..|> Command
TopoCommand ..|> Command


@enduml