@startuml
'https://plantuml.com/class-diagram

class Ui {
-Divider: String
+getUserInput(): void
+printWelcomeMessage(): void
+printExitMessage(): void
+printHelpPage(): void
+printAddSuccess(): void
+printListSuccess(): void
+printRemoveSuccess(): void
+printFilterFail(): void
+printInvalidCommand(): void
+printSaveFail(): void
+printFileWriteError(): void
+printInvalidNote(): void
+printTopoSortSuccess(): void
}

package Command <<Rectangle>> {
}

CLIAlgo--> "1" Ui

FileManager --> "1    " Ui
FileManager *- "*" SingleFile
SingleFile --> "1  " Ui

Command ..> Ui

@enduml