@startuml
skinparam classAttributeIconSize 0

class FileManager {
-path: String
-topicRawData: HashMap<String, SingleFile>
-topicNames: Arraylist<String>
+initialize()
+createSingleFile()
+addEntry(name: String, cs2040cFile: CS2040CFile)
+deleteEntry(cs2040cFileName: String)
}

class SingleFile {
-storedRawData: HashMap<String, String>
-cs2040cFiles: HashMap<String, CS2040CFile>
+readFile()
+recreateFile()
+writeCS2040CFileToFile(fileName: String, encodedCS2040CFile: String, cs2040cFile: CS2040CFile)
+deleteEntry(name: String)
+convertFileToTopic(): Topic
}

class FileDecoder {
+decodeString(encodedCS2040CFile: String, topicName: String): boolean
}

class FileEncoder {
+encodeCS2040CFile(name: String, cs2040cFile: CS2040CFile): String
}

class File {
+createNewFile()
}

class Topic {
}

class CS2040CFile {
}

class Scanner {
+nextLine()
}

class FileWriter {
+write()
}

FileManager --> "1" FileEncoder
FileManager *- "*" SingleFile
SingleFile --> "1" FileDecoder
SingleFile --> "1" File
SingleFile -- Topic : creates >
SingleFile .. FileWriter : passes string to >
File .. FileWriter : writes to <
SingleFile .. Scanner : updates storedRawData <
File .. Scanner : passes string to >
CS2040CFile .. FileManager : gets reference from <
CS2040CFile .. FileEncoder : gets reference from <
Topic *- "*" CS2040CFile

hide circle
@enduml
