@startuml
!include ../../style.iuml
skinparam classAttributeIconSize 0
hide circle

abstract class Command Command_STYLE{
    +execute(topicManager: TopicManager, ui: Ui, fileManager: FileManager, buffer: Buffer): void
}

class ListCommand ListCommand_STYLE{
    +execute(topicManager: TopicManager, ui: Ui, fileManager: FileManager, buffer: Buffer): void
}

class TopicManager TopicManager_STYLE{
}

class Ui Ui_STYLE{
}

class Buffer Buffer_STYLE{
}

class FileManager FileManager_STYLE{
}

Command <|-- ListCommand

TopicManager .. ListCommand
Ui .. ListCommand
FileManager .. ListCommand
Buffer .. ListCommand
@enduml