@startuml
!include ../../style.iuml
hide footbox

participant ":FileManager" as FileManager FileManager_STYLE
participant ":FileEncoder" as FileEncoder FileEncoder_STYLE
participant ":SingleFile" as SingleFile SingleFile_STYLE
participant ":FileWriter" as FileWriter
participant ":BufferedWriter" as BufferedWriter
participant ":File" as File

activate FileManager
-> FileManager : addEntry
FileManager -> FileEncoder : encode
FileEncoder --> FileManager : encodedCS2040CFile: String
FileManager -> SingleFile : writeCS2040CFileToFile
activate SingleFile
    opt file does not exist
        SingleFile -> SingleFile : recreateFile()
        activate SingleFile
        deactivate SingleFile
        SingleFile -> SingleFile : overwriteFile()
        activate SingleFile
        SingleFile -> File
        activate File
        deactivate File
        deactivate SingleFile
    end
SingleFile -> FileWriter **
activate FileWriter
FileWriter -> BufferedWriter **
activate BufferedWriter
BufferedWriter -> File : write(encodedCS2040CFile: String)
activate File
BufferedWriter -> File : newLine()
deactivate File
BufferedWriter -> BufferedWriter : close()
activate BufferedWriter
deactivate BufferedWriter
destroy BufferedWriter
FileWriter -> FileWriter : close()
activate FileWriter
deactivate FileWriter
destroy FileWriter
@enduml