@startuml
hide footbox

participant ": AddCommand" as AddCommand
participant ": InvalidTopicCommand" as InvalidTopicCommand
participant ": AddNoteCommand" as AddNoteCommand
participant "fileManager: FileManager" as FileManager
participant "topicManager: TopicManager" as TopicManager
participant ": InvalidCommand" as InvalidCommand
participant "ui: Ui" as Ui

-> AddCommand : execute()
activate AddCommand
    opt CS2040CFile does not exist in directory
        AddCommand -> Ui : printFileDoesNotExist()
        activate Ui
        return
        <-- AddCommand
    end

    opt topicName is not valid
        AddCommand -> InvalidTopicCommand **
        activate InvalidTopicCommand
        return

        AddCommand -> InvalidTopicCommand: execute()
        activate InvalidTopicCommand
        return
        destroy InvalidTopicCommand
        <-- AddCommand
    end

    opt is CS2040CFile is repeated
        AddCommand -> Ui : printCS2040CFileExists()
        activate Ui
        return
    end

    alt CS2040CFile type is txt
        AddCommand -> AddNoteCommand **
        activate AddNoteCommand
        return

        AddCommand -> AddNoteCommand : execute()
        activate AddNoteCommand
            AddNoteCommand -> FileManager : addEntry()
            activate FileManager
            return isAddedToFile: boolean

            opt CS2040CFile is not added to fileManager
                AddNoteCommand --> AddCommand
                <-- AddCommand
            end

            AddNoteCommand -> TopicManager : addCS2040CFile()
            activate TopicManager
            return isAdded: boolean

            opt CS2040CFile is not added to topicManager
                AddNoteCommand -> InvalidCommand **
                activate InvalidCommand
                return

                AddNoteCommand -> InvalidCommand : execute()
                activate InvalidCommand
                return
                destroy InvalidCommand
            end
            return
            destroy AddNoteCommand
            <-- AddCommand
    end
    AddCommand -> Ui : printAddSuccess()
    activate Ui
    return
return
destroy AddCommand

@enduml