@startuml
hide footbox
participant ": AddCommand" as a
participant ": InvalidTopicCommand" as it
participant ": AddNoteCommand" as an
participant "fileManager: FileManager" as fm
participant "topicManager: TopicManager" as tm
participant ": InvalidCommand" as ic
participant "ui: Ui" as ui

-> a : execute()
activate a
    opt CS2040CFile does not exist in directory
        a -> ui : printFileDoesNotExist()
        activate ui
        return
        <-- a
    end

    opt topicName is not valid
        a -> it **
        activate it
        return

        a -> it: execute()
        activate it
        return
        destroy it
        <-- a
    end

    opt is CS2040CFile is repeated
        a -> ui : printCS2040CFileExists()
        activate ui
        return
    end

    alt CS2040CFile type is txt
        a -> an **
        activate an
        return

        a -> an : execute()
        activate an
            an -> fm : addEntry()
            activate fm
            return isAddedToFile: boolean

            opt CS2040CFile is not added to fileManager
                an --> a
                <-- a
            end

            an -> tm : addCS2040CFile()
            activate tm
            return isAdded: boolean

            opt CS2040CFile is not added to topicManager
                an -> ic **
                activate ic
                return

                an -> ic : execute()
                activate ic
                return
                destroy ic
            end
            return
            destroy an
            <-- a
    end
    a -> ui : printAddSuccess()
    activate ui
    return
return
destroy a

@enduml