@startuml
actor User
participant "cliAlgo: CLIAlgo" as CLIAlgo
participant "ui: Ui" as Ui
participant "parser: Parser" as Parser
participant ": Command" as Command

activate CLIAlgo
    loop fullCommand != "exit"
    User -> CLIAlgo
    CLIAlgo -> Ui : getUserInput()
    activate Ui
    return fullCommand : String

    CLIAlgo -> Parser : parse(fullCommand: String)
    activate Parser
        Parser -> Command **
        activate Command
        return
    return command : Command

    CLIAlgo -> Command : execute()
    activate Command
    return
    destroy Command
    end
destroy CLIAlgo
destroy Ui
destroy Parser
@enduml