@startuml
hide footbox

actor User
participant "cliAlgo: CLIAlgo" as CLIAlgo
participant "ui: Ui" as Ui
participant "parser: Parser" as Parser
participant ": Command" as Command
box logic
participant "topicManager: TopicManager" as TopicManager
participant ": Topic" as Topic
end box
participant "buffer: Buffer" as Buffer
box storage
participant "fileManager: FileManager" as FileManager
participant ": SingleFile" as SingleFile
end box

activate CLIAlgo
    loop fullCommand != "exit"
    User -> CLIAlgo
    CLIAlgo -> Ui : getUserInput()
    activate Ui
    return fullCommand : String

    CLIAlgo -> Parser : parse(fullCommand: String)
    activate Parser
        Parser -> Command **
        activate Command
        return
    return command : Command

    CLIAlgo -> Command : execute()
    activate Command
        Command -> TopicManager
        activate TopicManager
            TopicManager -> Topic
            activate Topic
            return
        return

        Command -> Buffer
        activate Buffer
        return

        Command -> FileManager
        activate FileManager
            FileManager -> SingleFile
            activate SingleFile
            return
        return
    return
    destroy Command
    end
@enduml