@startuml
hide footbox
!include ../../style.iuml

participant ": ExportCommand" as ExportCommand ExportCommand_STYLE
participant "buffer: Buffer" as Buffer Buffer_STYLE
participant ": EmptyBufferCommand" as EmptyBufferCommand EmptyBufferCommand_STYLE
participant "ui: Ui" as Ui Ui_STYLE

-> ExportCommand: execute()
activate ExportCommand
    ExportCommand -> Buffer: isEmpty()
    activate Buffer
    return :boolean

    opt buffer is empty
        ExportCommand -> EmptyBufferCommand **
        activate EmptyBufferCommand
        return

        ExportCommand -> EmptyBufferCommand: execute()
        activate EmptyBufferCommand
            EmptyBufferCommand -> Ui: printBufferEmpty()
            activate Ui
            return
        return
        destroy EmptyBufferCommand
        <-- ExportCommand
    end

    ExportCommand -> Ui: printExportSuccess()
    activate Ui
    return
    ExportCommand -> Buffer: exportBuffer()
    activate Buffer
    return
return
destroy ExportCommand
@enduml