@startuml
-> FilterCommand : execute()
activate FilterCommand
    opt topicManger.isEmpty()
        FilterCommand -> Ui : printFilterEmpty()
        activate Ui
        return
        FilterCommand -> Buffer : updateBuffer(filteredFiles : ArrayList<CS2040CFile>)
        activate Buffer
        return
    end
    alt keyWord.equals("topic")
        FilterCommand -> FilterByTopicCommand **
        activate FilterByTopicCommand
        return

        FilterCommand -> FilterByTopicCommand : execute()
        activate FilterByTopicCommand
            alt topic == null
                FilterByTopicCommand -> FilterByTopicCommand : printAllTopics()
                activate FilterByTopicCommand
                    FilterByTopicCommand -> TopicManager : getAllCS2040CFilesGroupedByTopic()
                    activate TopicManager
                    return toPrintCS2040CFiles: HashMap<String, ArrayList<String>>

                    FilterByTopicCommand -> Ui : printFilterSuccess()
                    activate Ui
                    return

                    loop toPrintCS2040CFiles
                        FilterByTopicCommand -> Ui : printListOfCS2040CFiles(currentTopicCS2040CFiles)
                        activate Ui
                        return
                    end
                return
            else else
                FilterByTopicCommand -> FilterByTopicCommand : printSingleTopic()
                activate FilterByTopicCommand
                    FilterByTopicCommand -> TopicManager : getAllCS2040CFilesByTopic()
                    activate TopicManager
                    return toPrintCS2040CFiles: ArrayList<String>

                    FilterByTopicCommand -> Ui : printFilterSuccess()
                    activate Ui
                    return

                    FilterByTopicCommand -> Ui : printListOfCS2040CFiles(toPrintCS2040CFiles)
                    activate Ui
                    return
                return
            end
        return
        destroy FilterByTopicCommand
    else keyWord.equals("importance")
    else else
    end
return
destroy FilterCommand
@enduml