@startuml
participant "parser: Parser" as Parser
participant "<<interface>> \n StringManipulation" as StringManipulation
participant ": InvalidCommand" as InvalidCommand
participant ": RemoveCommand" as RemoveCommand

-> Parser : parse(fullCommand : String)
activate Parser
    Parser -> StringManipulation : getFirstWord(fullCommand : String)
    activate StringManipulation
    return command : String

    alt !isValidCommand(command)
        Parser -> InvalidCommand **
        activate InvalidCommand
        return
    else else
        Parser -> StringManipulation : removeFirstWord(fullCommand : String)
        activate StringManipulation
        return description : String

        Parser -> Parser : prepareCommand(command : String, description : String, topics : TopicManager)
        activate Parser
            alt command == "help"
            else command == "add"
            else command == "remove"
                Parser -> Parser : PrepareRemoveCommand (description : String, topics : TopicManager)
                activate Parser
                    alt description == null || !isCorrectMarker(description)
                        Parser -> InvalidCommand **
                        activate InvalidCommand
                        return
                    else
                        Parser -> StringManipulation : RemoveMarker(description : String)
                        activate StringManipulation
                        return cs2040cFileName

                        Parser -> RemoveCommand **
                        activate RemoveCommand
                        return RemoveCommand
                    end
                return
            else command == "filter"
            else command == "list"
            else command == "export"
            else command == "topo"
            else
            end
        return
    end
return command: Command

@enduml