@startuml
!include ../../style.iuml
hide footbox

participant ": RemoveCommand" as r RemoveCommand_STYLE
participant "topicManager: TopicManager" as tm TopicManager_STYLE
participant "fileManager: FileManager" as fm FileManager_STYLE
participant "ui: Ui" as ui Ui_STYLE
participant "buffer: Buffer" as b Buffer_STYLE

-> r : execute()
activate r RemoveCommand_STYLE
    opt topic manager is empty
        r -> ui : printRemoveFail()
        activate ui Ui_STYLE
        return
        <-- r
    end

    opt CS2040CFile is not inside topic manager
        participant ": NameNotFoundCommand" as nn NameNotFoundCommand_STYLE
        r -> nn **
        activate nn NameNotFoundCommand_STYLE
        return

        r -> nn : execute()
        activate nn NameNotFoundCommand_STYLE
        return
        destroy nn
        <-- r
    end

    r -> tm : removeCS2040CFile
    activate tm TopicManager_STYLE
    return

    opt CS2040CFile NOT successfully removed from topic manager
        r -> ui : printRemoveFail
        activate ui Ui_STYLE
        return
        <-- r
    end

    r -> fm : recreateAll()
    activate fm FileManager_STYLE
    return

    r -> fm : deleteEntry()
    activate fm FileManager_STYLE
    return

    opt CS2040CFile NOT deleted from file manager
        <-- r
    end

    r -> b : updateBuffer()
    activate b Buffer_STYLE
    return

    r -> ui : printRemoveSuccess()
    activate ui Ui_STYLE
    return
    return
    destroy r

@enduml