@startuml
hide footbox

participant ":ListCommand" as ListCommand
participant "ui: Ui" as Ui
participant "in: Scanner" as Scanner
participant "System.out" as System

-> Ui: getUserInput()
activate Ui
    Ui -> Scanner: nextLine()
    activate Scanner
    return :String
return fullCommand: String

-> ListCommand: execute()
activate ListCommand
    ListCommand -> Ui: printListOfCS2040CFiles()
    activate Ui
        loop cs2040cFiles
            Ui -> System: println(cs2040cFile: String)
            activate System
            return
        end
    return
return
destroy ListCommand

@enduml
