@startuml
hide footbox

participant ":ListCommand" as ListCommand
participant "ui: Ui" as Ui
participant "in: Scanner" as Scanner
participant "System.out" as System

-> Ui: getUserInput()
activate Ui
alt Successful case
    Ui -> Scanner: nextLine()
    activate Scanner
    note right of Scanner : User Input: `list`
    return :String
    <-- Ui : fullUserInput
else NoSuchElementException
    Ui -> Ui : printReadFail()
    activate Ui
    return
    <-- Ui : EXIT_COMMAND
else IllegalStateException
    Ui -> Ui : printReadFail()
    activate Ui
    return
    <-- Ui : EXIT_COMMAND
end

-> ListCommand: execute()
activate ListCommand
    ListCommand -> Ui: printListOfCS2040CFiles()
    activate Ui
        loop cs2040cFiles
            Ui -> System: println(cs2040cFile: String)
            activate System
            return
        end
    return
return

destroy ListCommand

@enduml
