@startuml

participant HelpCommand as hc
participant Ui as ui

activate hc
 -> hc **
<-- hc
deactivate hc
 -> hc : execute()
 activate hc
activate ui
    alt null
    hc -> ui : ui.printHelpPage()
    ui --> hc
    else add
    hc -> ui : ui.printHelpAdd()
    ui --> hc
    else remove
    hc -> ui : ui.printHelpRemove()
    ui --> hc
    else filter
    hc -> ui : ui.printHelpFilter()
    ui --> hc
    else topo
    hc -> ui : ui.printHelpTopo()
    ui --> hc
    else list
    hc -> ui : ui.printHelpList()
    ui --> hc
    else exit
    hc -> ui : ui.printHelpExit()
    ui --> hc
   end
deactivate ui
<-- hc

@enduml