@startuml
'https://plantuml.com/sequence-diagram

actor User as u
participant CLIAlgo as cli
participant Parser as p
participant TopoCommand as tc
participant TopicManager as tm

u -> cli : `topo n/noteName`
activate cli
cli -> p : prepareTopoCommand()
deactivate cli
activate p
p --> tc **
activate tc
deactivate p
tc --> cli
deactivate tc
activate cli
deactivate tc
cli -> tc : execute
deactivate cli
activate tc
tc -> tm
activate tm
tm --> tc
deactivate tm
tc -> tc : printTopoSortedCS2040CFiles(topicManager : TopicManager, ui : Ui)
activate tc
tc -> tm : getAllCS2040CFilesBeforeTopic(name : String)
activate tm
tm --> tc
deactivate tm
loop topicName
    tc -> tc : printSingleTopic(topicName : String)
end
tc --> tc
destroy tc
tc --> cli
cli --> u

@enduml